/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import Persistência.UsuarioDAO;
import java.awt.event.KeyEvent;

/**
 *
 * @author evert
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        txtUsua = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jButton3.setText("Entrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtUsua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuaKeyTyped(evt);
            }
        });

        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSenhaKeyTyped(evt);
            }
        });

        jLabel1.setText("Usuário:");

        jLabel2.setText("Senha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsua, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
        
        UsuarioDAO dao = new UsuarioDAO();
       if(dao.checkLogin(txtUsua.getText(), txtSenha.getText())){
           new Inicializadora(dao.checkAdmin(txtUsua.getText(), txtSenha.getText())).setVisible(true);
           this.dispose();
       }else{
           JOptionPane.showMessageDialog(null, "Usuário ou senha incorreta ou inválidos!");
       }        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtUsuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuaKeyTyped
       
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuaKeyTyped

    private void txtSenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaKeyTyped

    
    private void txtUsuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuaKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER){
            if(txtUsua.getText()!=null && txtSenha.getText()!=null){
           
        
        UsuarioDAO dao = new UsuarioDAO();
       if(dao.checkLogin(txtUsua.getText(), txtSenha.getText())){
           new Inicializadora(dao.checkAdmin(txtUsua.getText(), txtSenha.getText())).setVisible(true);
           this.dispose();
       }else{
           JOptionPane.showMessageDialog(null, "Usuário ou senha incorreta ou inválidos!");
       }
        }else{
            JOptionPane.showMessageDialog(null, "Nenhum campo pode estar vazio para fazer login!");
        }
        }
            
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuaKeyPressed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
 if (evt.getKeyChar() == KeyEvent.VK_ENTER){
            if(txtUsua.getText()!=null && txtSenha.getText()!=null){
            
        
        UsuarioDAO dao = new UsuarioDAO();
       if(dao.checkLogin(txtUsua.getText(), txtSenha.getText())){
           new Inicializadora(dao.checkAdmin(txtUsua.getText(), txtSenha.getText())).setVisible(true);
           this.dispose();
       }else{
           JOptionPane.showMessageDialog(null, "Usuário ou senha incorreta ou inválidos!");
       }
        }else{
            JOptionPane.showMessageDialog(null, "Nenhum campo pode estar vazio para fazer login!");
        }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsua;
    // End of variables declaration//GEN-END:variables
}
